Repository tinkerbell/ipxedust, pull requests merged in 2022-11, with the labels that each got.

#47 Add chrisdoherty4 as approver
  .github/settings.yml
Labels: ready-to-merge

#46 Update iPXE binary to latest. Apply vcreate patch:
  Makefile
  binary/script/fetch_and_extract_ipxe.sh
  binary/script/ipxe.commit
  binary/script/vcreate.patch
Labels: kind/bug, ready-to-merge

#49 Remove vcreate patching:
  Makefile
  binary/script/fetch_and_extract_ipxe.sh
  binary/script/ipxe.commit
  binary/script/vcreate.patch
Labels: kind/bug
